### ISSUE TITLE
[Request] chown / chmod the backup files

### ISSUE THREAD

**Issue by DanTheMan827** [Kaiede/docker-minecraft-bedrock-backup#11]
I'm running this on my unraid server, and I have to force UID to 0 and GID to 100, this is fine, but this results in files owned by root:users and a permission of 644

Typically, files created by unraid are owned by nobody with a group of users and have a permission of 666

This isn't a huge issue, but it does result in some permission issues.

Being able to specify the owner, group, and permissions of the newly created backup files would be useful in this case.

**Comment by Kaiede** [comment]
Yeah, unfortunately, `nobody` really shouldn't have access to docker, so the existing mechanisms aren't suitable for this specific use case where the service and backup directory need to have different ownership semantics. Let me take a look to see what can be done here.

**Comment by Kaiede** [comment]
The ability to chown the file after backing it up does mean that automatic trimming may not be able to function properly if the user the service runs under doesn't have write permission to the file. So a couple things that need to be thought through as part of implementing this:

- Can conflicts between the ownership configuration and the trimming configuration be detected before hitting permission errors trying to trim? This would make configuration errors a little more obvious.  
- Should the ability to change ownership be mutually exclusive with the ability to trim without the above? Or should it just attempt to trim anyways with a warning, and throw errors otherwise?

**Comment by DanTheMan827** [comment]
I guess it depends on the environment that it's running in really.

In my case, the docker environment for this container is running as root (yes, I know...), so permissions wouldn't be a problem.

Another way you could do things is by creating a persistent socket inside the docker container with `docker attach` for each minecraft server instance that can be accessed by anything inside the container

Docker can be annoying when you're dealing with permissions for sure.

**Comment by Kaiede** [comment]
I've done some basic work here and pushed it to the dev tag. It adds options to the config JSON:

```
...
  "ownership": {
    "chown": "(UID):(GID)",
    "permissions": "644"
  }
...
```

The chown string supports pretty much everything the chown command itself does, _except_ it can't take user names, only IDs. I haven't had time to test it yet, but if you want to poke at it, feel free.

**Comment by Kaiede** [comment]
I've rejiggered things, and now anything checked into `main` on BedrockifierCLI and the docker container project will show up automatically under the `test` tag, which will be how I deliver early looks at changes before they hit the `latest` tag.

Since the changes don't seem to regress anything, and I've been focusing on a couple other issues at the moment, this work is now in the `test` tag, just undocumented for now. I still intend to get around to testing this feature, but I wanted to clear out some of the other issues while I had some good momentum going.

**Comment by Kaiede** [comment]
Okay, so this feature isn't working all that well... need to debug to see what's up:

* Chown doesn't work at all, even when root. 
* Permissions seem to be getting distorted somehow when getting applied. "664" becomes "221".

The latter seems to be a bug in Foundation on Linux, but will need to try this again using glibc instead to remove that variable.

**Comment by Kaiede** [comment]
Interestingly, chown seems busted in Foundation on Linux. Permissions *were* working, but I made the mistake of assuming the bitfield was hex rather than octal.

With the PR merged, and this in the test tag now, I'm closing out the item. Like the other item, I'll be moving this to latest once it's had a few days bake time, probably this weekend.
